osx_image: xcode61
language: objective-c

cache:
  - bundler

before_script:
  - make ci

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec pod install

script:
  - make test
  - make lint

notifications:
  slack:
    secure: "SdMjQW614Ev8d9aReDhNUukENTmCcTIdqC88OuI0k4GKjsH12mZznGbAKUqtEKz2N0K+WA/EGL8QOWwmtgcL8qy5HuwwTwZzXvyRWG/ononJj3QqQf5+iVUF4eTt4Y+7CY3Njt1iW4nFSS0tWtORSc63epKYeNvsKLx1AK92fvo="
